project/event_management_system/admin_portal/urls.py
from django.urls import path
from .views import login_view, books_view, add_book_view, edit_book_view, delete_book_view, dahboard_events_view
from .views import events_view, add_event_view, edit_event_view, delete_event_view, participants_view
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('login/', login_view, name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("books/", books_view, name="books"),
    path("add_book/", add_book_view, name="add_book"),
    path("edit_book/<int:pk>/", edit_book_view, name="edit_book"),
    path("delete_book/<int:pk>/", delete_book_view, name="delete_book"),
    path("events/", events_view, name="events"),
    path("add_event/", add_event_view, name="add_event"),
    path("edit_event/<int:pk>/", edit_event_view, name="edit_event"),
    path("delete_event/<int:pk>/", delete_event_view, name="delete_event"),
    path("participants/<int:pk>/", participants_view, name="participants"),
]

project/event_management_system/event_management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from admin_portal.views import events_view, participants_view, dahboard_events_view
urlpatterns = [
	path("", dahboard_events_view, name="dahboard_events"),
    path("admin/", include("admin_portal.urls")),
    path("user/", include("user_portal.urls")),
]

project/event_management_system/user_portal/urls.py
from django.urls import path
from .views import login_view,  register_view, dashboard_view, participate_view, exit_participate_view
from django.contrib.auth.views import LogoutView

urlpatterns = [

    path('register/', register_view, name="signup"),
    path("login/", login_view, name="signin"),
    path("logout/", LogoutView.as_view(), name="signout"),
    path("dashboard/", dashboard_view, name="dashboard"),
    path("participate/<int:pk>/", participate_view, name="participate"),
    path("exit_participate/<int:pk>/", exit_participate_view, name="exit_participate"),
]

project/event_management_system/admin_portal/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Author(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    email = models.EmailField()

    def __str__(self):
        return u'%s %s' % (self.first_name, self.last_name)

class Book(models.Model):
    title = models.CharField(max_length=80)
    description = models.TextField(max_length=250)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    publication_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.title

class Event(models.Model):

    event_name = models.CharField(max_length=50)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    participant = models.ManyToManyField(User)
    maximum_participants = models.PositiveSmallIntegerField()
    
    def __str__(self):
        return self.event_name

project/event_management_system/admin_portal/forms.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django import forms
from django.core.validators import validate_email
from .models import Author, Book, Event
from django.forms import ModelForm
from django.contrib.admin.widgets import AdminDateWidget
import datetime

class LoginForm(forms.Form):
    email = forms.CharField(
        widget=forms.EmailInput(
            attrs={
                "placeholder" : "Email",                
                "class": "form-control",
                "autocomplete" : "off"
            }
        ), validators=[validate_email])
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder" : "Password",                
                "class": "form-control",
                "autocomplete" : "off"
            }
        ))


class BookAddForm(ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder" : "Title",                
                "class": "form-control"
            }
        ))
    description = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "placeholder" : "Description",                
                "class": "form-control"
            }
        ))

    author = forms.ModelChoiceField(
        queryset = Author.objects.all(),
        empty_label = "Select Author",
        widget=forms.Select(
            attrs={
                "placeholder" : "Author",                
                "class": "form-control"
            },
        ))

    class Meta:
        model = Book
        fields = ['title', 'description', 'author']


class EventAddForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(EventAddForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        if instance and instance.pk and instance.start_date < datetime.datetime.now().date():
            self.fields['start_date'].widget.attrs['readonly'] = True

        if instance and instance.pk and instance.end_date < datetime.datetime.now().date():
            self.fields['end_date'].widget.attrs['readonly'] = True

    event_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder" : "Event Name",                
                "class": "form-control"
            }
        ))

    book = forms.ModelChoiceField(
        queryset = Book.objects.all(),
        empty_label = "Select Book",
        widget=forms.Select(
            attrs={
                "placeholder" : "Book",                
                "class": "form-control"
            },
        ))

    start_date = forms.DateTimeField(
        input_formats=['%d/%m/%Y'],
        widget=forms.DateInput(format=('%d/%m/%Y'),
            attrs={
            "placeholder" : "Select date", 
            'class': 'form-control',
        }))

    end_date = forms.DateTimeField(
        input_formats=['%d/%m/%Y'],
        widget=forms.DateInput(format=('%d/%m/%Y'),
            attrs={
            "placeholder" : "Select date", 
            'class': 'form-control',
        })
    )

    maximum_participants = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={
                'min': '1',
                "placeholder" : "Maximum Participants",                
                "class": "form-control"
            }
        ))

    class Meta:
        model = Event
        fields = ['event_name', 'start_date', 'end_date','maximum_participants','book']

project/event_management_system/admin_portal/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .forms import LoginForm, BookAddForm, EventAddForm
from django.contrib import messages
from .models import Author, Book, Event
from django.contrib.auth.decorators import user_passes_test
import datetime

def get_user(email):
    try:
        return User.objects.get(email=email.lower())
    except User.DoesNotExist:
        return None

def login_view(request):
    if request.user.is_authenticated and request.user.is_superuser:
        return redirect("books")
    elif request.user.is_authenticated and not request.user.is_superuser:
        return redirect("dashboard")

    context = {'page_name' : 'admin-login'}
    form = LoginForm(request.POST or None)

    context['msg'] = None
    context['form_errors'] = None
    if request.method == "POST":

        if form.is_valid():
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")
            
            username = get_user(email)
            user = authenticate(username=username, password=password)
            
            if user is not None and username.is_superuser:
                login(request, user)
                return redirect(request.GET.get('next',"books"))
            else:    
                context['msg'] = 'Invalid credentials'    
        else:
            context['msg'] = 'Please fill the required fields'
            context['form_errors'] = form.errors.as_json()
    context['form'] = form

    return render(request, "login.html", context)

@user_passes_test(lambda u: u.is_superuser)
@login_required
def books_view(request):
    context = {}
    context['page_name'] = 'books'
    context['book_data'] = Book.objects.all()

    return render(request, "books.html", context)

@user_passes_test(lambda u: u.is_superuser)
@login_required
def add_book_view(request):
    context = {}
    context['page_name'] = 'books'

    form = BookAddForm(request.POST or None)

    context['form_errors'] = None
    if request.method == "POST":

        if form.is_valid():
            form.save()
            messages.success(request, 'Book has been added successfully.')
            return redirect("books")
        else:
            context['form_errors'] = form.errors.as_json()

    context['form'] = form
    return render(request, "add_book.html", context)

@user_passes_test(lambda u: u.is_superuser)
@login_required
def edit_book_view(request, pk):
    context = {}
    context['page_name'] = 'books'
    context['page_edit'] = 'edit'
    context['form_errors'] = None
    book = get_object_or_404(Book, pk=pk)
    form = BookAddForm(request.POST or None , instance = book)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            messages.success(request, 'Book has been updated successfully.')
            return redirect('books')
        else:
            context['form_errors'] = form.errors.as_json()
    context['form'] = form
    return render(request, "add_book.html", context)

@user_passes_test(lambda u: u.is_superuser)
@login_required
def delete_book_view(request, pk):
    book = get_object_or_404(Book, pk=pk)    
    book.delete()
    messages.success(request, 'Book has been deleted successfully.')
    return redirect('books')

@user_passes_test(lambda u: u.is_superuser)
@login_required
def events_view(request,index=False):

    context = {}
    context['page_name'] = 'events'
    context['book_data'] = Event.objects.all()

    return render(request, "events.html", context)

@user_passes_test(lambda u: u.is_superuser)
@login_required
def add_event_view(request):
    context = {}
    context['page_name'] = 'events'

    form = EventAddForm(request.POST or None)

    context['form_errors'] = None
    if request.method == "POST":

        if form.is_valid():
            form.save()
            messages.success(request, 'Event has been added successfully.')
            return redirect("events")
        else:
            context['form_errors'] = form.errors.as_json()

    context['form'] = form
    return render(request, "add_event.html", context)

@user_passes_test(lambda u: u.is_superuser)
@login_required
def edit_event_view(request, pk):
    context = {}
    context['page_name'] = 'events'
    context['page_edit'] = 'edit'
    context['form_errors'] = None
    event = get_object_or_404(Event, pk=pk)
    form = EventAddForm(request.POST or None , instance = event)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            messages.success(request, 'Event has been updated successfully.')
            return redirect('events')
        else:
            context['form_errors'] = form.errors.as_json()
    context['form'] = form
    return render(request, "add_event.html", context)

@user_passes_test(lambda u: u.is_superuser)
@login_required
def delete_event_view(request, pk):
    event = get_object_or_404(Event, pk=pk)    
    event.delete()
    messages.success(request, 'Event has been deleted successfully.')
    return redirect('events')

@user_passes_test(lambda u: u.is_superuser)
@login_required
def participants_view(request, pk, index=False):
    
    context = {}
    context['page_name'] = 'events'
    event = Event.objects.get(id=pk)
    context['event_name'] = event
    context['participant_data'] = event.participant.all()
    
    return render(request, "participants.html", context)

def dahboard_events_view(request):

    context = {}
    context['page_name'] = 'events'
    context['book_data'] = Event.objects.filter(end_date__gte=datetime.date.today())

    return render(request, "dashboard_events.html", context)

project/event_management_system/admin_portal/templates/add_book.html
{% extends "layouts/base.html" %}

{% block title %} UI Tables {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
<style type="text/css">
  .row, .navbar .container-fluid { justify-content: center; }
  .bold {color: black !important; font-weight: bold;}
</style>
{% endblock stylesheets %}

{% block content %}

    <div class="row">
            <div class="col-md-8">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title">{% if page_edit %} Edit {% else %} Add {% endif %} Book</h4>
                </div>
                <div class="card-body">
                  <form role="form" method="post" action="" autocomplete="off" novalidate>
              
                    {% csrf_token %} 

                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <label class="bold">{{ form.title.label }} : </label>
                          {{ form.title }}
                          <span class="text-danger">{{ form.title.errors.as_text }}</span>
                        </div>
                      </div>
                    </div>

                    <br />

                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <label class="bold">{{ form.description.label }} : </label>
                          {{ form.description }}
                          <span class="text-danger">{{ form.description.errors.as_text }}</span>
                        </div>
                      </div>
                    </div>


                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <label class="bold">{{ form.author.label }} : </label>
                          {{ form.author }}
                          <span class="text-danger">{{ form.author.errors.as_text }}</span>
                        </div>
                      </div>
                    </div>

                    <br />

                    <button type="submit" name="save" class="btn btn-primary pull-left">{% if page_edit %} Update {% else %} Save {% endif %}</button>

                    &nbsp; &nbsp; 
                    

                    <div class="clearfix"></div>

                  </form>
                </div>
              </div>
            </div>
            
          </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

project/event_management_system/admin_portal/templates/add_event.html
{% extends "layouts/base.html" %}

{% block title %} UI Tables {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
<style type="text/css">
  .row, .navbar .container-fluid { justify-content: center; }
   .bold {color: black !important; font-weight: bold;}
</style>
{% endblock stylesheets %}

{% block content %}

    <div class="row">
            <div class="col-md-8">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title">{% if page_edit %} Edit {% else %} Add {% endif %} Event</h4>
                </div>
                <div class="card-body">
                  <form role="form" method="post" action="" autocomplete="off" novalidate>
              
                    {% csrf_token %} 

                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <label class="bold">{{ form.event_name.label }} : </label>
                          {{ form.event_name }}
                          <span class="text-danger">{{ form.event_name.errors.as_text }}</span>
                        </div>
                      </div>
                    </div>

                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <label class="bold">{{ form.book.label }} : </label>
                          {{ form.book }}
                          <span class="text-danger">{{ form.book.errors.as_text }}</span>
                        </div>
                      </div>
                    </div>


                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <label class="bold">{{ form.start_date.label }} : </label>
                          {{ form.start_date }}
                          <span class="text-danger">{{ form.start_date.errors.as_text }}</span>
                        </div>
                      </div>
                    </div>

                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <label class="bold">{{ form.end_date.label }} : </label>
                          {{ form.end_date }}
                          <span class="text-danger">{{ form.end_date.errors.as_text }}</span>
                        </div>
                      </div>
                    </div>

                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <label class="bold">{{ form.maximum_participants.label }} : </label>
                          {{ form.maximum_participants }}
                          <span class="text-danger">{{ form.maximum_participants.errors.as_text }}</span>
                        </div>
                      </div>
                    </div>

                    

                    <br />

                    <button type="submit" name="save" class="btn btn-primary pull-left">{% if page_edit %} Update {% else %} Save {% endif %}</button>

                    &nbsp; &nbsp; 
                    

                    <div class="clearfix"></div>

                  </form>
                </div>
              </div>
            </div>
            
          </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
<script type="text/javascript">
  $("#id_start_date:not([readonly])").datetimepicker({
      format: 'd/m/Y',
       timepicker:false,
       minDate : "0",
       onShow:function( ct ){
         this.setOptions({
          maxDate:jQuery('#id_end_date').val()?jQuery('#id_end_date').val():false
         })
       }
    });
  $("#id_end_date:not([readonly])").datetimepicker({
      format: 'd/m/Y',
       timepicker:false,
       minDate : "0",
       onShow:function( ct ){
         this.setOptions({
          minDate:jQuery('#id_start_date').val()?jQuery('#id_start_date').val():false
         })
        },
    });
</script>

{% endblock javascripts %}

project/event_management_system/admin_portal/templates/books.html
{% extends "layouts/base.html" %}

{% block title %} UI Tables {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
<style type="text/css">
  .row, .navbar .container-fluid { justify-content: center; }
  .dataTables_filter { float: right; }
</style>
{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-8">

        {% if messages  %}
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <i class="material-icons">close</i>
            </button>
            {% for message in messages %}
                    <span>
                      {{message }} </span>
            {% endfor %}
                  </div>
        {% endif %}
            <div class="card">
                <div class="card-header card-header-primary">
                    <h4 class="card-title " style=" margin-top: 12px; position: absolute;">Books </h4> 
                    <a href="{% url 'add_book' %}" class="btn btn-info pull-right">Add Book<div class="ripple-container"></div></a>
                </div>
                <div class="card-body">
                    <div>
                        <table id="data-list-table" class="table">
                            <thead class=" text-primary">
                                <th>Title</th>
                                <th>Description</th>
                                <th>Author</th>
                                <th>Action</th>
                            </thead>
                            <tbody>
                              {% for data in book_data %}
                              <tr>
                              <td>{{data.title}}</td>
                              <td>{{data.description}}</td>
                              <td>{{data.author}}</td>
                              <td><a href="/admin/edit_book/{{data.id}}/" title="Edit" class="action-icon">Edit</a> | <a href="/admin/delete_book/{{data.id}}/" title="Delete" class="action-icon">Delete</a>
                              </td>
                              {% endfor%}
                              </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

<script type="text/javascript">
  var oTable=$('#data-list-table').DataTable({
    scrollY: false,
    scrollX: false,
    paging: false,
    bInfo:false,
    iDisplayLength: -1,
    columnDefs: [{ 'orderable': false, 'targets': -1 }],
});
</script>

{% endblock javascripts %}

project/event_management_system/admin_portal/templates/dashboard_events.html
{% extends "layouts/base.html" %}

{% block title %} UI Tables {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
<style type="text/css">
  .row, .navbar .container-fluid { justify-content: center; }
  .dataTables_filter { float: right; }
</style>
{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-8">

        {% if messages  %}
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <i class="material-icons">close</i>
            </button>
            {% for message in messages %}
                    <span>
                      {{message }} </span>
            {% endfor %}
                  </div>
        {% endif %}
            <div class="card">
              {% if user.is_authenticated %}
                
                <div class="card-header card-header-primary" style="padding-bottom:  30px;">
                    <h4 class="card-title " style="  position: absolute;">Events </h4> 
                </div>
                    {% endif %}
                <div class="card-body">
                    <div>
                        <table id="data-list-table" class="table">
                            <thead class=" text-primary">
                                <th>Event Name</th>
                                <th>Book</th>
                                <th>Start Date</th>
                                <th>End Date</th>
                                
                            </thead>
                            <tbody>
                              {% for data in book_data %}
                              <tr>
                              <td>{{data.event_name}}</td>
                              <td>{{data.book}}</td>
                              <td>{{data.start_date}}</td>
                              <td>{{data.end_date}}</td>
                              
                              {% endfor%}
                              </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

<script type="text/javascript">
  var oTable=$('#data-list-table').DataTable({
    scrollY: false,
    scrollX: false,
    paging: false,
    bInfo:false,
    iDisplayLength: -1,
    columnDefs: [{ 'orderable': false, 'targets': -1 }],
});
</script>

{% endblock javascripts %}

project/event_management_system/admin_portal/templates/events.html
{% extends "layouts/base.html" %}

{% block title %} UI Tables {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
<style type="text/css">
  .row, .navbar .container-fluid { justify-content: center; }
  .dataTables_filter { float: right; }
</style>
{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-8">

        {% if messages  %}
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <i class="material-icons">close</i>
            </button>
            {% for message in messages %}
                    <span>
                      {{message }} </span>
            {% endfor %}
                  </div>
        {% endif %}
            <div class="card">
              {% if user.is_authenticated %}
                <div class="card-header card-header-primary">
                    <h4 class="card-title " style=" margin-top: 12px; position: absolute;">Events </h4> 
                    <a href="{% url 'add_event' %}" class="btn btn-info pull-right">Add Event<div class="ripple-container"></div></a>
                </div>
                {% else %}
                <div class="card-header card-header-primary" style="padding-bottom:  30px;">
                    <h4 class="card-title " style="  position: absolute;">Events </h4> 
                </div>
                    {% endif %}
                <div class="card-body">
                    <div>
                        <table id="data-list-table" class="table">
                            <thead class=" text-primary">
                                <th>Event Name</th>
                                <th>Book</th>
                                <th>Start Date</th>
                                <th>End Date</th>
                                {% if user.is_authenticated %}
                                <th>Participants</th>
                                <th>Action</th>
                                {% endif %}
                            </thead>
                            <tbody>
                              {% for data in book_data %}
                              <tr>
                              <td>{{data.event_name}}</td>
                              <td>{{data.book}}</td>
                              <td>{{data.start_date}}</td>
                              <td>{{data.end_date}}</td>
                              {% if user.is_authenticated %}
                              <td><a href="/admin/participants/{{data.id}}/" title="View" class="action-icon">View</a></td>
                              <td><a href="/admin/edit_event/{{data.id}}/" title="Edit" class="action-icon">Edit</a> | <a href="/admin/delete_event/{{data.id}}/" title="Delete" class="action-icon">Delete</a>
                              </td>
                              {% endif %}
                              {% endfor%}
                              </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

<script type="text/javascript">
  var oTable=$('#data-list-table').DataTable({
    scrollY: false,
    scrollX: false,
    paging: false,
    bInfo:false,
    iDisplayLength: -1,
    columnDefs: [{ 'orderable': false, 'targets': -1 }],
});
</script>

{% endblock javascripts %}

project/event_management_system/admin_portal/templates/login.html
{% extends "layouts/base.html" %}

{% block title %} Login {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}

<style type="text/css">
  .row, .navbar .container-fluid { justify-content: center; }
  .bold {color: black !important; font-weight: bold;}
</style>

{% endblock stylesheets %}

{% block content %}

  <div class="row">
    <div class="col-md-5">
      <div class="card">
        <div class="card-header card-header-primary">
          <h4 class="card-title">
            Admin Login
          </h4>
        </div>
        <div class="card-body">

          <h6 class="card-category">
              {% if msg %}
                <span class="text-danger">{{ msg | safe }}</span>
              {% endif %}  
          </h6>
          
          <br />

          <form role="form" method="post" action="" autocomplete="off" novalidate>
              
            {% csrf_token %} 

            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label class="bold">{{ form.email.label }}</label>
                  {{ form.email }}
                  <span class="text-danger">{{ form.email.errors.as_text }}</span>
                </div>
              </div>
            </div>

            <br />

            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label class="bold">{{ form.password.label }}</label>
                  {{ form.password }}
                  <span class="text-danger">{{ form.password.errors.as_text }}</span>
                </div>
              </div>
            </div>

            <br />

            <button type="submit" name="login" class="btn btn-primary pull-left">Login</button>

            &nbsp; &nbsp; 
            

            <div class="clearfix"></div>

          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

<script type="text/javascript">
  $(document).ready(function () {
      $(".form-group").addClass("is-filled")
  });
</script>

{% endblock javascripts %}